### PR TITLE
Ensure imported module changes trigger compilation

### PR DESCRIPTION
**Pull request by FranzSkuffka**
Right now changes to imported modules did not trigger compilation.

This should do the job.

### CODE REVIEW

**Comment by hmsk** [comment]
Thanks for your continuous contribution! Great point, I didn't care about the case outside of HMR works. You're not using HMR for some reason...?
To release this PR's changes easily, could you update your changes to build without any TS errors? Or I'm going to work on next week.

**Comment by FranzSkuffka** [comment]
Honestly I don't know how to enable HMR in that case? Can you please provide instructions? There is no info in the readme.

**Comment by hmsk** [comment]
HMR is enabled as default by vite :) so, what does this PR solves exactly?
When modifying an imported module, this plugin triggers HMR for that (then the imported module is compiled and replaced on the fly).

Probably, I miss something you would point. It’d be great if you give a minimum reproducible codes and procedures to understand the situation.

Anyways this PR makes sense for non-HMR situation since this plugin doesn’t build dependency graph out side of HMR so far.

**Comment by FranzSkuffka** [comment]
So for me, changing an imported module did in fact NOT trigger a re-compilation. Only when I changed the Main.elm.

Are you sure you tested this for elm applications with more than one file?

**Comment by hmsk** [comment]
You can try with the sample project under `/example`. When updating `Message.elm` which is imported by `Main.elm`, `Message.elm` is replaced with re-compilation actually.

https://user-images.githubusercontent.com/85887/119428610-0ba56c80-bcc2-11eb-9882-a26fcd7f0301.mp4

That's why I'm curious about your case. thanks for dedicating your time to dig into it!

**Comment by FranzSkuffka** [comment]
Okay interesting, I will see if the problem persists on a fresh install and report back. Thank you for your time.

**Comment by FranzSkuffka** [comment]
You were right. My problem was actually related to something else. See #16

**Pull request closed without merging**
